[package]
name = "art-dl"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
phf = { version = "0.10.1", features = ["macros"] }
rusqlite = "0.27.0"
serde_json = "1.0.79"
url = "2.2.2"
