[package]
name = "art-dl"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
# rusqlite = "0.27.0"
serde_json = "1.0.79"
sqlx = { version = "0.6.2", features = ["sqlite", "json", "runtime-tokio-rustls"] }
tokio = { version = "1.25.0", features = ["full"] }
url = "2.2.2"
